### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by urbie-mk2** [ChrisAntaki/disable-speculative-pre-connections#1]
Thanks for the addon. Icon.png used for the addon summary page seems missing in root dir of addon xpi

**Comment by ChrisAntaki** [comment]
Good call @dbruenig !

https://github.com/ChrisAntaki/disable-speculative-pre-connections/commit/e637524d8391306bbd32073b4d8db66a041cce54 fixed this, and a new version is waiting to be reviewed on AMO
